### ISSUE TITLE
Author Created Posts are initially Unapproved

### ISSUE THREAD

**Issue by hannahhall** [nss-day-cohort-48/rare-api-boastful-bulldogs#24]
As an admin I would like Posts written by non-admin users (a.k.a. "Authors") to be initially unapproved, so that authors are unable to publish any inappropriate Posts without oversight.

> **NOTE:** If an admin writes a Post it should be automatically approved.

**Comment by gqgonzales** [comment]
Back End: Edit the `model/post.py` to include a key:value for `approved:false`. Don't forget to `makemigrations` and `migrate`!
