### ISSUE TITLE
Admins Can Approve Posts

### ISSUE THREAD

**Issue by hannahhall** [nss-day-cohort-48/rare-api-boastful-bulldogs#25]
As an admin I would like the ability to approve Posts that I deem appropriate so that the system can provide quality content.

**Comment by gqgonzales** [comment]
Front End: Add conditional column to `post/PostList.js` that hosts checkboxes for approval. When checked, `!approved`.

Back End: Edit `views/post.py` to make sure the `def update` on approved posts is functioning.
